---
blank_issues_enabled: false
contact_links:
  - name: Data Model Community Support
    url: https://github.com/developer-academy-unina/Workshop-Data-Model/discussions
    about: Please ask and answer questions here.
